### PR TITLE
fix #1193

### LINKED ISSUE #1193: duplicate code in commands.js
There is duplicate code in `commands.js` that convert call to client (`RedisClient` or `Multi`) to a `Command` ([line 32](https://github.com/leibale/node_redis/blob/master/lib/commands.js#L32), [line 74](https://github.com/leibale/node_redis/blob/master/lib/commands.js#L74)).

### PR DESCRIPTION
**Pull request by leibale**
Delete duplicate code and export `callToCommand` function

### CODE REVIEW

**Comment by BridgeAR** [comment]
The arguments would leak and this is a significant performance decrease.

**Comment by leibale** [comment]
What? Can you elaborate?

**Comment by BridgeAR** [comment]
```js
var Benchmark = require('benchmark')
var suite = new Benchmark.Suite()

function clone (args) {
  var arr = new Array(args.length)
  for (var i = 0; i < args.length; i++) {
    arr[i] = args[i]
  }
  return arr
}

function noLeak () {
  var arr = new Array(arguments.length)
  for (var i = 0; i < arguments.length; i++) {
    arr[i] = arguments[i]
  }
  return arr
}

function leaks () {
  return clone(arguments)
}

suite.add('Does not leak', function () {
  noLeak(1, 2, 3)
})

suite.add('Leaks', function () {
  leaks(1, 2, 3)
})

suite.on('cycle', function (event) {
  console.log(String(event.target))
})

suite.run({ delay: 1, minSamples: 150 })
``` 
```
Does not leak x 50,351,674 ops/sec ±0.72% (90 runs sampled)
Leaks x 19,793,341 ops/sec ±1.94% (90 runs sampled)
```
[More info](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers) about this topic.

**Comment by BridgeAR** [comment]
Thanks for your effort though!

**Pull request closed without merging**
