### PR TITLE
Tiny speedup by removing command.toLowerCase()

### PR DESCRIPTION
**Pull request by BridgeAR**
This is not necessary as the command itself is only used from inside the code and as they are (now) all lower case it is safe to remove the toLowerCase.

### CODE REVIEW

**Comment by brycebaril** [comment]
This is breaks backwards compatibility, correct?

**Comment by BridgeAR** [comment]
Why should it be? I can't think of any way that a user could insert commands upper case that would not be handled.

**Comment by brycebaril** [comment]
Ahh, yes -- that's correct. The upperCase versions of the commands close the lowercase ones and call that.

Not sure we should lowercase all the tests, though, as this would reduce coverage, no? (Unless you added/left one to specifically test the uppercase commands?)

**Comment by BridgeAR** [comment]
I checked that there were always both versions and kept them as they were if there was only one version. But this would actually not matter for the coverage as the commands don't count towards the coverage :)

**Comment by bcoe** [comment]
This seems reasonable to me, while you're at it, it might be worth changing:

https://github.com/fintura/node_redis/blob/speedup/index.js#L1143

On this branch, so that it matches the pattern used elsewhere for exposing the upper and lowercase versions of each method.

**Comment by BridgeAR** [comment]
@bcoe I changed that in another PR, should I move that change into this one?

**Comment by BridgeAR** [comment]
Closing #605

**Pull request merged**
