### PR TITLE
Fetch new list of commands

### PR DESCRIPTION
**Pull request by qix**

### CODE REVIEW

**Comment by jonathanong** [comment]
:+1:

**Comment by jpbriend** [comment]
:+1:

**Comment by BridgeAR** [comment]
@qix would you mind updating the list again and adding a `'use strict';` in the file to generate the commands? It would be great to have some tests for the new commands but I'd say it's fine to merge them first and add tests for each command later.

What do you think @bcoe @erinspice?

**Comment by BridgeAR** [comment]
Superseded by #814

**Pull request closed without merging**
