### PR TITLE
Add support for TLS

### PR DESCRIPTION
**Pull request by paddybyers**
See https://github.com/mranney/node_redis/issues/246 for discussion.

### CODE REVIEW

**Comment by ananlvjiao** [comment]
+1 for Azure redis

**Comment by dayvson** [comment]
+1

**Comment by jbblanchet** [comment]
This pull request has been opened for over a year (and the underlying issue for 30 months). Is there something we can do to help you integrate this?

**Comment by danlash** [comment]
I've updated the code to fit with the new internal structure. It works empirically with redislabs+ssl but the tests don't work just yet. I'm new to stunnel, debugging through it now.

**Comment by pierreliefauche** [comment]
+1

**Comment by blicket** [comment]
+1

**Comment by BridgeAR** [comment]
@paddybyers would you still be up for this PR? I'd like to this support for this in node_redis

**Comment by danlash** [comment]
Yeah but it's been a while so I'd like to check it out next week. Have you tried this branch out?

**Comment by paddybyers** [comment]
> @paddybyers would you still be up for this PR?

I'm pretty sure it needs some work to rebase to latest master. I'm happy to look at it.

**Comment by BridgeAR** [comment]
@danlash I did not have any chance to try this yet but it would be great if you could do that instead. The new test suite is probably also helping with this

**Comment by BridgeAR** [comment]
@paddybyers that would be nice :)

**Comment by louisgv** [comment]
:+1:

**Comment by BridgeAR** [comment]
Ping :)

**Comment by paddybyers** [comment]
> Ping :)

I'm working on it; hopefully I can push something tomorrow (Monday).

**Comment by BridgeAR** [comment]
That would be great :)

**Comment by paddybyers** [comment]
Closing this in favour of https://github.com/NodeRedis/node_redis/issues/894.

**Pull request closed without merging**
