### PR TITLE
[WIP] Fix Command Queue Stack Error in PUBSUB mode

### LINKED ISSUE #603: Command Queue Stack Error
I'm trying to `SUBSCRIBE`/`UNSUBSCRIBE` from channels in the following way (minimal working example):

```
var client = require('redis').createClient();

function subscribe(channels) {
    client.unsubscribe(function (error) {
        console.log(error);
    });
    client.subscribe(channels, function (error) {
        console.log(error);
    });
}

subscribe(['1', '3']);
subscribe(['2']);
```

The idea is, at any moment, completely replace this list of subscribed channels with a different one. This immediately causes the following error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: node_redis command queue state error. If you can reproduce this, please report it.
    at RedisClient.return_reply (/myproject/node_modules/redis/index.js:705:15)
    at HiredisReplyParser.RedisClient.init_parser (/myproject/node_modules/redis/index.js:309:14)
    at HiredisReplyParser.emit (events.js:95:17)
    at HiredisReplyParser.execute (/myproject/node_modules/redis/lib/parser/hiredis.js:43:18)
    at RedisClient.on_data (/myproject/node_modules/redis/index.js:534:27)
    at Socket.stream.on.self.should_buffer (/myproject/node_modules/redis/index.js:91:14)
    at Socket.emit (events.js:95:17)
    at Socket.stream.pause.paused (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
```

Making the call to `client.subscribe` inside the callback passed to `client.unsubscribe` instead doesn't help. Wrapping the call to `client.subscribe` with `process.nextTick` seems to provide a workaround the problem. Any clues on how to solve this?

### PR DESCRIPTION
**Pull request by BridgeAR**
This is going to fix a couple of open tickets. I'm not really happy with the solution as is but at least the app does not crash anymore and it seems to work as it should. But there are likely still errors with the pubsub mode and this is probably not a good fix. It would be good if we'd find a better solution at some later point.

This superseds #685 (it somehow did not fix the issue in my tests?) and fixes #603 and #577

### CODE REVIEW

**Comment by BridgeAR** [comment]
@NodeRedis/contributors I'd like to have someone look at this, since I'm not so certain if this is a good way to handle it.

**Comment by blainsmith** [comment]
I would say for the sake of 2.0.0 we should get this in, but make an issue for further investigation. I would even throw a "help wanted" tag on the issue to get some community feedback on a possible refactor.

**Comment by bcoe** [comment]
@BridgeAR when you have a moment, mind rebasing this with master; I want to see if the Windows failures stop cropping up.

**Comment by BridgeAR** [comment]
@bcoe I have to rework this again. I think I got a way to fix this more approriate, but I have to find the time to do so.

**Pull request closed without merging**
