### PR TITLE
Add promisify example for node.js 8

### PR DESCRIPTION
**Pull request by 1999**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Comment by 1999** [comment]
I'm pretty sure build fails because of smth different.

**Comment by LiranBri** [comment]
oops, I just sent PR for the same purpose (https://github.com/NodeRedis/node_redis/pull/1284)
however, I think mine is more detailed a bit

**Comment by 1999** [comment]
Good catch. I think it's also worth it to have async/await example in your PR as well @LiranBri

**Comment by LiranBri** [comment]
sure i'll add one

**Pull request closed without merging**
