### PR TITLE
feat(parser): update to latest Redis parser & errors

### PR DESCRIPTION
**Pull request by WarmVissarutRonaldoDude**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

- update `redis-parser` to `3.0.0` for removing `hiredis` to support node 12+.
- fix eslint errors.
- fix some of existing errors.
- add nodejs 12 to travis ci.
- add nodejs 12 to appveyor ci.

### CODE REVIEW

**Comment by WarmVissarutRonaldoDude** [comment]
@DanielSeehausen Hi!!

about removal `call` in `lib/customErrors` is because

`call` is not working with ES6 class constructor without `new keyword` and after look into the code for both `old` and `modern` in `redis-error` I saw it's only set `message` to `this.message` which we also set it in any `customErrors` here so I think we can just remove it instead of add complexity here to solving old and modern compat. :)

Reference: https://github.com/NodeRedis/redis-errors/blob/master/lib/modern.js

**Comment by DanielSeehausen** [comment]
> @DanielSeehausen Hi!!
> 
> about removal `call` in `lib/customErrors` is because
> 
> `call` is not working with ES6 class constructor without `new keyword` and after look into the code for both `old` and `modern` in `redis-error` I saw it's only set `message` to `this.message` which we also set it in any `customErrors` here so I think we can just remove it instead of add complexity here to solving old and modern compat. :)
> 
> Reference: https://github.com/NodeRedis/redis-errors/blob/master/lib/modern.js

thank you for the explanation! sounds good

**Comment by adylevy** [comment]
Can someone provide an update on this one? really need to get rid of hiredis...

**Comment by zhangshirly** [comment]
Can someone provide an update on this one? really need to get rid of hiredis... please，i don't want to change to ioredis

**Pull request merged**
