### PR TITLE
Remove send_command safety checks

### PR DESCRIPTION
**Pull request by BridgeAR**
This checks are only important for users who use send_command directly instead of using the convenience method.
As the readme clearly states how send_command should work and any user would have run into errors if misused, these checks can be removed. If any user might misuse the function anyway, it is very likely that another error will be thrown because of that

### CODE REVIEW

**Comment by BridgeAR** [comment]
This is no BC btw, since if a user would have used the function wrong before, an error would have been thrown. So there should not be any code that relies on this behavior.

**Comment by BridgeAR** [comment]
This could be skipped in the 2.0 release but I think it could be included as well.

**Comment by bcoe** [comment]
I don't know if I agree with this change from a usability standpoint, at npm we're in the habit of asserting at the top of methods that the function signature is correct:

https://github.com/ceejbot/numbat-emitter/blob/master/lib/emitter.js#L16

This is a good way to give immediate feedback to a user that they're using the API in the wrong way. What's the argument for removing the safety checks? I could see how it could benefit performance slightly, did you run any benchmarks?

**Comment by BridgeAR** [comment]
@bcoe using send_command directly should not often be the case but all other users and commands run through these safety checks. It should not impact the speed a lot (I did not run any benchmark as I could not think of a proper way to write a benchmark that would only test these statements. The multi_bench benchmark is not reliable on (the output varies a lot by each run and v8 is probably optimizing a lot away) but it should be a tiny bit.
I tried out all possibilities that we prevent users from doing wrong and all are going to throw errors at some point.
As this makes the code better to read and is a small speedup in most cases I think it's reasonable to merge this.

**Comment by BridgeAR** [comment]
This should fix #629 
TODO: Add a test for a case where omitting is fine

**Pull request merged**
