### PR TITLE
feat(commands): update redis-commands version

### PR DESCRIPTION
**Pull request by knoxcard**
update redis-commands and redis-parser

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Comment by sookoll** [comment]
When it will be merged? node_redis is not usable in Node 12, as there is redis-parser 2.6, which has hiredis dependency.

**Comment by WarmVissarutRonaldoDude** [comment]
with this changes it will break this line
https://github.com/NodeRedis/node_redis/blob/a60261da0461d4bb114b1533fada87e97fa985c8/lib/customErrors.js#L42

as seem like `RedisError` is not export from `redis-parser: 3.0.0`
FYI: https://github.com/NodeRedis/node-redis-parser/pull/34/files

**Comment by szagi3891** [comment]
Does that mean the library's dead? Well, I guess we'll have to find another library to handle redis.

**Comment by stockholmux** [comment]
@szagi3891 not dead - this PR just needs to be modified.

**Comment by szagi3891** [comment]
It would be nice to bring this "PR" to integration with the main branch. Currently it is not possible to run this library in 12 nodejs versions.

**Comment by stockholmux** [comment]
@szagi3891 ..humm. I just tested it with v12.13.0 and it worked. How does it 'not work'?

**Comment by szagi3891** [comment]
@stockholmux 

These are the logs from my application. Installation not possible

```
iMac-Grzegorz:gpp-website-4 grzegorz$ node --version
v12.13.0
iMac-Grzegorz:gpp-website-4 grzegorz$ rm -Rf node_modules/
iMac-Grzegorz:gpp-website-4 grzegorz$ npm install 

> fsevents@1.2.9 install /Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/chokidar/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> fsevents@1.2.9 install /Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/jest-haste-map/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/jest-haste-map/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> deasync@0.1.15 install /Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/deasync
> node ./build.js

`darwin-x64-node-12` exists; testing
Binary is fine; exiting

> fsevents@1.2.9 install /Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/nodemon/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> fsevents@1.2.9 install /Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/webpack-dev-server/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/webpack-dev-server/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> hiredis@0.5.0 install /Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/hiredis
> node-gyp rebuild

  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  LIBTOOL-STATIC Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
../src/reader.cc:21:17: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        larray->Set(task->idx,v);
                ^
/Users/grzegorz/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/grzegorz/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/reader.cc:55:33: error: no matching member function for call to 'ToString'
        v = Exception::Error(v->ToString());
                             ~~~^~~~~~~~
/Users/grzegorz/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2572:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/grzegorz/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2588:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
1 warning and 1 error generated.
make: *** [Release/obj.target/hiredis/src/reader.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/grzegorz/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/grzegorz/.nvm/versions/node/v12.13.0/bin/node" "/Users/grzegorz/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/grzegorz/Desktop/Projects/gpp-website-4/node_modules/hiredis
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN gpp-website@1.0.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hiredis@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiredis@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/grzegorz/.npm/_logs/2019-11-04T08_30_58_391Z-debug.log
iMac-Grzegorz:gpp-website-4 grzegorz$ 
```

**Comment by stockholmux** [comment]
@szagi3891 I can only get that type of error by installing `hiredis` directly - you shouldn't get this error unless you're installing devDependencies.

**Comment by justinberry** [comment]
We've just upgraded to node 12, and while the library seems to be working we're receiving a bunch of DeprecationWarnings because redis-parser uses a deprecated Buffer constructor. Is there any progress on getting this PR fixed/merged?

**Pull request merged**
