### PR TITLE
Add delay option for socket.setKeepAlive

### PR DESCRIPTION
**Pull request by betimer**
### Pull Request check-list

- [ ] Does `npm test` pass with this change (including linting)?
- [X] Is the new or changed code fully tested?
- [X] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### Description of change

Add option for socket_initialdelay when calling socket.setKeepAlive from node API

### CODE REVIEW

**Comment by betimer** [comment]
This is critical as because of this issue: https://github.com/nodejs/node/issues/24689

**Comment by stockholmux** [comment]
I'm going to go ahead and merge, but I think we should investigate the root cause here as we might need a default that isn't 0.

**Comment by betimer** [comment]
@stockholmux I strongly agree to have a value which is not the default 0.
Created this PR to add the option but does not change the existing behaviour.
I think something like 5000~60000 milliseconds would be fine.

I can make the change if this sounds OK, also may i know when we might get the new version?

**Comment by stockholmux** [comment]
I consulted with some colleagues on this. I don't think there is actually a rational/universal initial delay default. I'm ok with this as-is.

**Comment by betimer** [comment]
Nice. no worries, as long as this already provides an interface to whom, like us, facing the issue, to change the setting. Thank you @stockholmux

**Comment by RidgeA** [comment]
Hi @betimer !
Is it possible to the latest version of the library from NPM?
As I can see the library version was updated on NPM more than a year ago...

**Comment by Fundebug** [comment]
@anhzhi I found that idle redis connection will be disconnected every 2 hours, it is strange. It is solved by using your code:

```javascript
client.on('connect', function () {
    var socket = client.stream
    socket.setKeepAlive(true, 30 * 1000)
})
```

**Comment by RidgeA** [comment]
This would work, but it is an ugly workaround. There is a special option for this, the package just need to be updated on npm. We have switched to ioredis package.

**Comment by thameezb** [comment]
This contains a typo on the option. `socket_initialdelay` vs `socket_initial_delay` as used in other locations

**Pull request merged**
