### PR TITLE
Fix travis ci testing

### PR DESCRIPTION
**Pull request by Apollon77**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm test` pass with this change (including linting)?
- [n/a] Is the new or changed code fully tested?
- [n/a] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### Description of change

Travis-CI has disabled IPv6 in their trusty images and thats why your tests failed since some time. because I rely on your work I thought it is a good idea to fix the testing. So I did :-)

### CODE REVIEW

**Comment by BridgeAR** [comment]
@Apollon77 thanks a lot! :+1: about the changed error message: I am not sure why the message is different on Windows and on Linux. I am going to investigate that.

**Comment by Apollon77** [comment]
Oh, oversaw the windows testing (I also have appveyor) ... Interesting ... shpuld I change to allow tests to accept both?

**Comment by BridgeAR** [comment]
@Apollon77 that would probably be the best. It does not matter if it is a specific message as long as we know that it returns the "appropriate" message.

**Comment by Apollon77** [comment]
Done. Appveyor also green (in general, only a nodejs 0.10 timing issue happened)

**Comment by BridgeAR** [comment]
Thabks a lot for your contribution!

**Pull request merged**
