### PR TITLE
Fix for channel names with spaces

### PR DESCRIPTION
**Pull request by pbihler**
Fix for #691

### CODE REVIEW

**Comment by brycebaril** [comment]
Please include a test

**Comment by laino** [comment]
His 2 lines of code appear to do what they are supposed to, unsurprisingly:

```js
var key = "holy fgdfsf cow"
var space_index = key.indexOf(" ")
var parts = [key.slice(0,space_index), key.slice(space_index+1)]
console.log(parts)
// [ 'holy', 'fgdfsf cow' ]
```

**Comment by brycebaril** [comment]
@laino it's not that I don't trust the code, it's that tests ensure this remains working at every release. If you want to write the test as a part of this or another pull request that would be fine, you're about halfway there with your comment.

**Comment by BridgeAR** [comment]
@pbihler would you be so kind and add a test? Otherwise LGTM

**Comment by BridgeAR** [comment]
Fixed by 97db227a8d2098f82472b08e107e02532e73616d

Thx @pbihler :)

**Pull request closed without merging**
