### PR TITLE
ignore if info command is not available on server

### PR DESCRIPTION
**Pull request by ivanB1975**
I added some lines to ignore if the "info" command is not available on the server for security reason.

### CODE REVIEW

**Comment by BridgeAR** [comment]
Please add a test and use the same style as used in the rest of the code.

Otherwise LGTM

**Comment by ivanB1975** [comment]
Sure, I will see if I have time today.

**Comment by BridgeAR** [comment]
Thx, I merged your commits and it will be released with 2.3

**Comment by ivanB1975** [comment]
You're welcome :)

**Pull request closed without merging**
