### PR TITLE
change `times_connected` to `attempt` in the `retry_strategy`

### LINKED ISSUE #1214: Incorrect retry strategy in README.md
The retry strategy in the example does not appear to be correct. The last check, is `times_connected > 10`. I believe that this should be `attempt > 10`.

Current behavior, `times_connected > 10`, would terminate the retries after the client has connected to the server `11` times.

Expected behavior, `attempt > 10`, would terminate the retries after the client has failed to reconnect 10 times in a row.

### PR DESCRIPTION
**Pull request by abramz**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

Change the documentation for `retry_strategy` to terminate after 10 attempts, not after the client has successfully connected 10 times.

Resolves #1214

### CODE REVIEW

**Comment by abramz** [comment]
Note on those failing tests. Completely unrelated to a change in the README.md

[AppVeyor](https://ci.appveyor.com/project/BridgeAR/node-redis/build/364-bnxbtuop/job/hh6a6yvmn1d5qbhs#L1690)
[Travis CI](https://travis-ci.org/NodeRedis/node_redis/jobs/211921493#L491)

**Comment by stockholmux** [comment]
Thanks for the addition. I usually work on documentation issues. I've been abroad for the past week and I'll review when I get back next week.

**Comment by abramz** [comment]
No worries, thanks @stockholmux

**Comment by BridgeAR** [comment]
In the end both is correct as it's just a example. But I don't feel strong of either way.

So thanks for your input.

**Pull request merged**
