### PR TITLE
Updating the test filename and description to match the command under test

### PR DESCRIPTION
**Pull request by mattberther**
It's the little things :)

### CODE REVIEW

**Comment by BridgeAR** [comment]
@mattberther [merged](b14cbaf1d517ca040bbc1107bbd167ec92428c00), thanks a lot! :+1:

**Comment by mattberther** [comment]
Thanks @BridgeAR. 

Im not sure the entire pull request was merged though. The file rename commit didnt appear to come through -- in NodeRedis:master, its still called exits.js.

**Comment by BridgeAR** [comment]
You're absolutly right. It was just way to late in the night. Fixed on master. Thanks for pointing that out :)

**Comment by mattberther** [comment]
Thanks @BridgeAR. Github still shows that there are unmerged commits -- i just wanted to make sure that it was fine to delete the mattberther:exists_test_update branch, or was there more that needed to be done?

**Comment by BridgeAR** [comment]
I cherry-picked your commits instead of merging them. At times I also use `git am` instead of merging. So it's safe to delete the branch.

**Pull request closed without merging**
